### ISSUE TITLE
change groupId to eg. it.geosolutions

### ISSUE THREAD

**Issue by mprins** [geosolutions-it/jgridshift#1]
As there is at least another fork of jgridshift at https://github.com/floscher/jGridShift/releases which has made several releases over the past years it might be good to change the `groupId` here to eg `it.geosolutions` to prevent confusing update tool chains and people, though the split into a "core" and a "sample" artifact already provides some protection.

**Comment by aaime** [comment]
I'm hesitant to switch the package as it would imply that this is a GeoSolutions project, while this fork is really a practical decision to get a specific fix going, with no particular commitment to do further development on the package (other than maybe solving JDK induced issues).

**Comment by aaime** [comment]
Fixed in dc0cc5768341a0f4c125cb6a0c5f0ac4a0ea1e15
