### ISSUE TITLE
jgridshift 1.2 ships with au.com.objectix.jgridshift.jca package, dragging in an outdated JavaEE dependency

### ISSUE THREAD

**Issue by soc** [geosolutions-it/jgridshift#2]
Hi Andrea!

It seems that in https://github.com/geosolutions-it/jgridshift/commit/ad137426aa1e511ef552fdb1afd56bb3a483695c#diff-600376dffeb79835ede4a0b285078036R46 the jca directory was intended to be included, but it somehow ended up in the released 1.2 jar anyway. :-/

The javaee-api compile-time dependency is pretty bad, because usually an application container would supply it (it is also from May, 2013, so its likely that other software depends on newer versions of it).

Would it be possible to either exclude jca again, or at least split it to a separate module?

Let me know if I can help!

Thanks,

Simon

**Comment by aaime** [comment]
Hi @soc yeah that seems like a good idea, I just don't have time to work on it. Pull requests are welcomed though. First I think and understanding the issue is necessary, is it a build time problem (the jar contains deps that are not meant to be there, even locally), or it happened to be a deploy time issue.

**Comment by soc** [comment]
@aaime Ooooops:

> the jca directory was intended to be included

This meant to read

> the jca directory was intended to be **excluded**

>  is it a build time problem (the jar contains deps that are not meant to be there, even locally), or it happened to be a deploy time issue.

I hopefully will be able to have a look at it on the weekend.

**Comment by soc** [comment]
I'd probably just split it into two modules, because that makes it way easier to see what goes into which jar file, instead of trying to use exclusions.

**Comment by soc** [comment]
I just looked at the older published artifacts – did the JCA part ever get published?

I'd probably just move it to some other dir and drop it from the build altogether...

**Comment by soc** [comment]
It also seems the contents of the sample directory were deleted in https://github.com/soc/jgridshift/commit/d646dccd239d471b2f03e74d00af00fbd638a586#diff-5e8ff9bf55ba3508199d22e984129be6.

The sample dir does not contain any code anymore, is this intentional?

**Comment by soc** [comment]
@aaime Did some fixes, could you have a look at #3?
